-- ==========================================================================
-- SCHEMA DE SUPABASE PARA LABORATORIO DE ANATOMÍA PATOLÓGICA (ACTUALIZADO)
-- Copie y pegue este código en el "SQL Editor" de su panel de Supabase.
-- ==========================================================================

-- 1. Tabla de Pacientes (Informes)
CREATE TABLE IF NOT EXISTS pacientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service TEXT NOT NULL, -- 'Q', 'I', 'C'
    cod_atencion TEXT UNIQUE NOT NULL, -- Ej: '26Q-208'
    dni TEXT,
    med_solicitante TEXT,
    nombres TEXT,
    apellidos TEXT,
    paciente TEXT,
    costo NUMERIC DEFAULT 0,
    adelanto NUMERIC DEFAULT 0,
    resta NUMERIC DEFAULT 0,
    fec_registro DATE,
    fec_entrega DATE,
    pagado BOOLEAN DEFAULT false,
    atrasado BOOLEAN DEFAULT false,
    especimen TEXT,
    macro_desc TEXT,
    micro_desc TEXT,
    diagnostico TEXT,
    img01 TEXT,
    img02 TEXT,
    edad INTEGER,
    sexo TEXT,
    casetes INTEGER DEFAULT 1,
    f_contacto TEXT,
    tel_contacto TEXT,
    doctor TEXT,
    motivo_estudio TEXT,
    cat_macro TEXT,
    plan_macro TEXT,
    cat_micro TEXT,
    plan_micro TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabla de Doctores
CREATE TABLE IF NOT EXISTS doctores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    cmp TEXT,
    rne TEXT,
    tipo TEXT DEFAULT 'DR. CLIENTE',
    provincia TEXT,
    telefono TEXT,
    correo TEXT,
    firma TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabla de Usuarios
CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil TEXT, -- 'Administrador', 'Personal', 'Personal Biopath'
    dni TEXT,
    nombres TEXT,
    usuario TEXT UNIQUE,
    clave TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar acceso de lectura/escritura (Políticas RLS básicas para testing)
-- Nota: En producción, ajuste estas reglas de seguridad.
ALTER TABLE pacientes DISABLE ROW LEVEL SECURITY;
ALTER TABLE doctores DISABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios DISABLE ROW LEVEL SECURITY;

-- 4. Tabla de Plantillas
CREATE TABLE IF NOT EXISTS plantillas (
    id BIGINT PRIMARY KEY,
    "categoryId" BIGINT,
    titulo TEXT,
    macro TEXT,
    micro TEXT,
    diag TEXT,
    especialidad_nombre TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE plantillas DISABLE ROW LEVEL SECURITY;

-- Insertar datos iniciales de prueba (Pacientes)
INSERT INTO pacientes (service, cod_atencion, DNI, med_solicitante, nombres, apellidos, paciente, costo, adelanto, resta, fec_registro, fec_entrega, pagado, atrasado, especimen, macro_desc, micro_desc, diagnostico, edad, sexo)
VALUES 
('Q', '26Q-208', '0', 'DRA. LAURA SAIRE BOCANGEL', 'CLEOFE', 'CACCNAHUARAY HUILCAHUARI', 'CLEOFE CACCNAHUARAY HUILCAHUARI', 0, 0, 0, '2026-07-04', '2026-07-09', false, false, 'VESÍCULA BILIAR', 'Se recibe fragmentos de tejido. Se incluye todo.', 'Evaluación compatible con tejido remitido.', 'DIAGNOSTICO DE PRUEBA VESICULA BILIAR', 66, 'MASCULINO'),
('Q', '26Q-207', '0', 'DR. VICTOR CASTAÑEDA ROBLES', 'PEDRO', 'NEIRA HUCARPOMA', 'PEDRO NEIRA HUCARPOMA', 0, 0, 0, '2026-07-04', '2026-07-09', false, false, 'BIOPSIA GÁSTRICA', 'Se recibe fragmentos de tejido. Se incluye todo.', 'Evaluación compatible con tejido remitido.', 'GASTRITIS CRÓNICA NO ACTIVA.', 45, 'MASCULINO');

-- Insertar datos iniciales de prueba (Usuarios)
INSERT INTO usuarios (perfil, DNI, nombres, usuario, clave)
VALUES
('Administrador', '41457468', 'JOSEHP CHRISTOPHER , CASTILLO CUENCA', 'jcastillo', 'josehp789'),
('Administrador', '41092834', 'LAURA , SAIRE BOCANGEL', 'lsaire', 'laura789');
